language: go

go:
  - 1.8
  - 1.9
  - 1.10
  - 1.11
  - 1.12
  - tip

git:
  depth: 1

before_script:
  - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0

script:
  - golangci-lint run
  - go test -v -race ./...